### ISSUE TITLE
issues if the destination dashboard in trash

### ISSUE THREAD

**Issue by oferoh** [QuentinAmbard/databricks-sql-clone#1]
there is something that needs to be fixed,
in case of the dashboard + queries are in the trash in production,
the program still updating dashboard + queries from trash and does not create new dashboard + queries.
can you please update me if you managed to reproduce this?

**Comment by QuentinAmbard** [comment]
hi @oferoh, can you give it a try with the last version and let me know if the last commit fixes your issue?

**Comment by oferoh** [comment]
sure i will do that today

**Comment by oferoh** [comment]
@QuentinAmbard, I have checked this but looks like is not working, do you want to have a session together?

**Comment by QuentinAmbard** [comment]
hum ok I think it now works with queries in trash but not yet dashboard, I'll have a look.

**Comment by oferoh** [comment]
@QuentinAmbard any new? did you manage to solve this?

**Comment by QuentinAmbard** [comment]
can you try with the last version? It should be fixed

**Comment by oferoh** [comment]
@QuentinAmbard looks very good, many thanks
